"""Add rules schema

Revision ID: 3322ae0e6ed8
Revises: 30d0ac816cb7
Create Date: 2024-08-12 14:12:57.636237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3322ae0e6ed8'
down_revision: Union[str, None] = '30d0ac816cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
